version: "3.8"

services:
    backend:
        image: ${BACKEND_IMAGE}
        container_name: cloudpix-backend-staging
        ports:
            - "5001:5000" # Map ke port 5000 internal (sesuai backend Anda)
        environment:
            - NODE_ENV=staging
            - PORT=5000
            - DATABASE_URL=${DATABASE_URL:-postgresql://user:password@db:5432/cloudpix_staging}
        depends_on:
            - db
        networks:
            - cloudpix-staging
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
            interval: 30s
            timeout: 10s
            retries: 3

    frontend:
        image: ${FRONTEND_IMAGE}
        container_name: cloudpix-frontend-staging
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - cloudpix-staging
        restart: unless-stopped

    db:
        image: postgres:15-alpine
        container_name: cloudpix-db-staging
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=cloudpix_staging
        volumes:
            - postgres_staging_data:/var/lib/postgresql/data
        networks:
            - cloudpix-staging
        restart: unless-stopped

volumes:
    postgres_staging_data:

networks:
    cloudpix-staging:
        driver: bridge
