version: "3.9"

services:
    backend:
        image: ${BACKEND_IMAGE}:${IMAGE_TAG}
        env_file:
            - .env.production.backend
        environment:
            - NODE_ENV=production
        expose:
            - "5000"
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "wget -qO- http://localhost:5000/health || exit 1",
                ]
            interval: 30s
            timeout: 10s
            retries: 3

    frontend:
        image: ${FRONTEND_IMAGE}:${IMAGE_TAG}
        depends_on:
            - backend
        ports:
            - "80:80"
        restart: unless-stopped
