version: "3.8"

services:
    backend:
        image: ${BACKEND_IMAGE}
        container_name: cloudpix-staging-backend
        env_file:
            - .env.backend
        ports:
            - "5001:5000"
        environment:
            - NODE_ENV=staging
            - PORT=5000
        networks:
            - cloudpix-staging
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
            interval: 30s
            timeout: 10s
            retries: 3

    frontend:
        image: ${FRONTEND_IMAGE}
        container_name: cloudpix-staging-frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - cloudpix-staging
        restart: unless-stopped

volumes:
    postgres_staging_data:

networks:
    cloudpix-staging:
        driver: bridge
